module.exports = {
	SHOW_GRID	  	  	  	  		: 'SHOW_GRID',
	CHANGE_BORDER 	  	  	  		: 'CHANGE_BORDER',
	UPLOAD_ICON       	  	  		: 'UPLOAD_ICON',
	UPLOAD_BACKGROUND 	  	  		: 'UPLOAD_BACKGROUND',
	CHANGE_BACKGROUND 	  	  		: 'CHANGE_BACKGROUND',
	ICON_CHEKED		  	  	  		: 'ICON_CHEKED',
	CHANGE_COLOR_GRADIENT_TOP 		: 'CHANGE_COLOR_GRADIENT_TOP',
	CHANGE_COLOR_GRADIENT_BOTTOM 	: 'CHANGE_COLOR_GRADIENT_BOTTOM',
	GET_ICON_TO_DOWNLOAD 			: 'GET_ICON_TO_DOWNLOAD'
};