export const SHOW_GRID = 'SHOW_GRID';
export const CHANGE_BORDER = 'CHANGE_BORDER';
export const CHANGE_BACKGROUND_BOARD = 'CHANGE_BACKGROUND_BOARD';
export const CHANGE_GRADIENT_BOARD_TOP = 'CHANGE_BACKGROUND_BOARD_TOP';
export const CHANGE_BACKGROUND_BOARD_BOTTOM = 'CHANGE_BACKGROUND_BOARD_BOTTOM';